Add the latest working compilers to the travis build file
Some compilers were removed because they produced error that don't seem to be relevant anymore (semantic changes, straight up compiler crash etc):

```
dmd v2.066.1
source/derelict/imgui/types.d(756,21): Deprecation: variable derelict.imgui.types.ImFontConfig.GlyphRanges const field with initializer should be static, __gshared, or an enum
/home/travis/dlang/dmd-2.066.1/linux/bin64/../../src/druntime/import/core/stdc/stdarg.d(195,20): Error: no property 'va' for type 'const(char)*'
source/derelict/imgui/types.d(540,17): Error: template instance core.stdc.stdarg.va_start!(const(char)*) error instantiating
dmd failed with exit code 1.
```

```
dmd v2.065
source/derelict/imgui/types.d(756): Deprecation: variable derelict.imgui.types.ImFontConfig.GlyphRanges const field with initializer should be static, __gshared, or an enum
source/derelict/imgui/types.d(770): Error: module std.string import 'fromStringz' not found
dmd failed with exit code 1.
```

```
ldc 0.15.1
source/derelict/imgui/types.d(756,21): Deprecation: variable derelict.imgui.types.ImFontConfig.GlyphRanges const field with initializer should be static, __gshared, or an enum
source/derelict/imgui/funcs.d(112,70): Error: size of type ImGuiCol is not known
0  ldc2            0x000000000119ee72 llvm::sys::PrintStackTrace(_IO_FILE*) + 34
1  ldc2            0x000000000119ea24
2  libpthread.so.0 0x00007fe226d13330
3  libc.so.6       0x00007fe225e34943 _IO_vfprintf + 7427
4  libc.so.6       0x00007fe225e5b499 vsnprintf + 121
5  ldc2            0x00000000005fdaad OutBuffer::vprintf(char const*, __va_list_tag*) + 109
6  ldc2            0x00000000005fdb77 OutBuffer::printf(char const*, ...) + 135
7  ldc2            0x00000000005ddf8e Loc::toChars() + 46
8  ldc2            0x00000000006c9768 DtoType(Type*) + 744
9  ldc2            0x000000000072052e IrTypePointer::get(Type*) + 30
10 ldc2            0x00000000006c9580 DtoType(Type*) + 256
11 ldc2            0x000000000071ea5d IrFuncTyArg::IrFuncTyArg(Type*, bool, llvm::AttrBuilder) + 237
12 ldc2            0x0000000000707075 DtoFunctionType(Type*, IrFuncTy&, Type*, Type*, bool, bool, bool) + 1989
13 ldc2            0x00000000007227d8 IrTypeFunction::get(Type*, Type*) + 88
14 ldc2            0x00000000006c959a DtoType(Type*) + 282
15 ldc2            0x000000000072052e IrTypePointer::get(Type*) + 30
16 ldc2            0x00000000006c9580 DtoType(Type*) + 256
17 ldc2            0x00000000006b4b33 DtoResolveVariable(VarDeclaration*) + 467
18 ldc2            0x00000000006e81a1
19 ldc2            0x00000000006e71e3
20 ldc2            0x00000000006e811e Declaration_codegen(Dsymbol*) + 46
21 ldc2            0x00000000006e6921 Module::genLLVMModule(llvm::LLVMContext&) + 497
22 ldc2            0x00000000005a6cf5 main + 6325
23 libc.so.6       0x00007fe225e0af45 __libc_start_main + 245
24 ldc2            0x00000000005c45a5
Segmentation fault (core dumped)
ldc2 failed with exit code 139.
```

```
gdc 4.9.3
source/derelict/imgui/funcs.d:37:12: internal compiler error: in visit, at d/types.cc:47
     import derelict.imgui.types;
            ^
```